### ISSUE TITLE
Find a way to test the game without having a headset connected.

### ISSUE THREAD

**Issue by RealLankinen** [RealLankinen/spatial-breakout#1]
Right now if you hit the play button it just shows black screen and complains something about not having MR headset. We should be available to test it with keyboard and mouse or some other input method.

https://forum.unity.com/threads/how-best-to-test-vr-when-not-always-using-a-vr-headset.532265/

**Comment by tonysun83** [comment]
I'll try to investigate on my end regarding this issue as well
